USE DATABASE RONALDO;



select 
'SELECT ''' || column_name || ''' AS COLUMN_NAME,
SUM(CASE WHEN ' || column_name || ' IS NULL THEN 1 ELSE 0 END) AS NUM_NULLS,
SUM(CASE WHEN ' || column_name || ' IS NOT NULL THEN 1 ELSE 0 END) AS NUM_NOT_NULLS,
ROUND(NUM_NULLS / COUNT(*) * 100, 2) AS PERC_MISSING
FROM ' || table_schema || '.' || table_name || ' UNION ' AS QUERY
from information_schema.columns
where table_name like '%CR7_IMPORT%'
--where table_name like '%CR7_CLEANING%'
;




SELECT 'AREA_OF_SHOT' AS COLUMN_NAME, SUM(CASE WHEN AREA_OF_SHOT IS NULL THEN 1 ELSE 0 END) AS NUM_NULLS, SUM(CASE WHEN AREA_OF_SHOT IS NOT NULL THEN 1 ELSE 0 END) AS NUM_NOT_NULLS, ROUND(NUM_NULLS / COUNT(*) * 100, 2) AS PERC_MISSING FROM A_IMPORT.TT_CR7_IMPORT UNION 
SELECT 'DATE_OF_GAME' AS COLUMN_NAME, SUM(CASE WHEN DATE_OF_GAME IS NULL THEN 1 ELSE 0 END) AS NUM_NULLS, SUM(CASE WHEN DATE_OF_GAME IS NOT NULL THEN 1 ELSE 0 END) AS NUM_NOT_NULLS, ROUND(NUM_NULLS / COUNT(*) * 100, 2) AS PERC_MISSING FROM A_IMPORT.TT_CR7_IMPORT UNION 
SELECT 'DISTANCE_OF_SHOT' AS COLUMN_NAME, SUM(CASE WHEN DISTANCE_OF_SHOT IS NULL THEN 1 ELSE 0 END) AS NUM_NULLS, SUM(CASE WHEN DISTANCE_OF_SHOT IS NOT NULL THEN 1 ELSE 0 END) AS NUM_NOT_NULLS, ROUND(NUM_NULLS / COUNT(*) * 100, 2) AS PERC_MISSING FROM A_IMPORT.TT_CR7_IMPORT UNION 
SELECT 'DISTANCE_OF_SHOT_1' AS COLUMN_NAME, SUM(CASE WHEN DISTANCE_OF_SHOT_1 IS NULL THEN 1 ELSE 0 END) AS NUM_NULLS, SUM(CASE WHEN DISTANCE_OF_SHOT_1 IS NOT NULL THEN 1 ELSE 0 END) AS NUM_NOT_NULLS, ROUND(NUM_NULLS / COUNT(*) * 100, 2) AS PERC_MISSING FROM A_IMPORT.TT_CR7_IMPORT UNION 
SELECT 'GAME_SEASON' AS COLUMN_NAME, SUM(CASE WHEN GAME_SEASON IS NULL THEN 1 ELSE 0 END) AS NUM_NULLS, SUM(CASE WHEN GAME_SEASON IS NOT NULL THEN 1 ELSE 0 END) AS NUM_NOT_NULLS, ROUND(NUM_NULLS / COUNT(*) * 100, 2) AS PERC_MISSING FROM A_IMPORT.TT_CR7_IMPORT UNION 
SELECT 'HOME_AWAY' AS COLUMN_NAME, SUM(CASE WHEN HOME_AWAY IS NULL THEN 1 ELSE 0 END) AS NUM_NULLS, SUM(CASE WHEN HOME_AWAY IS NOT NULL THEN 1 ELSE 0 END) AS NUM_NOT_NULLS, ROUND(NUM_NULLS / COUNT(*) * 100, 2) AS PERC_MISSING FROM A_IMPORT.TT_CR7_IMPORT UNION 
SELECT 'ID' AS COLUMN_NAME, SUM(CASE WHEN ID IS NULL THEN 1 ELSE 0 END) AS NUM_NULLS, SUM(CASE WHEN ID IS NOT NULL THEN 1 ELSE 0 END) AS NUM_NOT_NULLS, ROUND(NUM_NULLS / COUNT(*) * 100, 2) AS PERC_MISSING FROM A_IMPORT.TT_CR7_IMPORT UNION 
SELECT 'IS_GOAL' AS COLUMN_NAME, SUM(CASE WHEN IS_GOAL IS NULL THEN 1 ELSE 0 END) AS NUM_NULLS, SUM(CASE WHEN IS_GOAL IS NOT NULL THEN 1 ELSE 0 END) AS NUM_NOT_NULLS, ROUND(NUM_NULLS / COUNT(*) * 100, 2) AS PERC_MISSING FROM A_IMPORT.TT_CR7_IMPORT UNION 
SELECT 'KNOCKOUT_MATCH' AS COLUMN_NAME, SUM(CASE WHEN KNOCKOUT_MATCH IS NULL THEN 1 ELSE 0 END) AS NUM_NULLS, SUM(CASE WHEN KNOCKOUT_MATCH IS NOT NULL THEN 1 ELSE 0 END) AS NUM_NOT_NULLS, ROUND(NUM_NULLS / COUNT(*) * 100, 2) AS PERC_MISSING FROM A_IMPORT.TT_CR7_IMPORT UNION 
SELECT 'KNOCKOUT_MATCH_1' AS COLUMN_NAME, SUM(CASE WHEN KNOCKOUT_MATCH_1 IS NULL THEN 1 ELSE 0 END) AS NUM_NULLS, SUM(CASE WHEN KNOCKOUT_MATCH_1 IS NOT NULL THEN 1 ELSE 0 END) AS NUM_NOT_NULLS, ROUND(NUM_NULLS / COUNT(*) * 100, 2) AS PERC_MISSING FROM A_IMPORT.TT_CR7_IMPORT UNION 
SELECT 'LOCATION_X' AS COLUMN_NAME, SUM(CASE WHEN LOCATION_X IS NULL THEN 1 ELSE 0 END) AS NUM_NULLS, SUM(CASE WHEN LOCATION_X IS NOT NULL THEN 1 ELSE 0 END) AS NUM_NOT_NULLS, ROUND(NUM_NULLS / COUNT(*) * 100, 2) AS PERC_MISSING FROM A_IMPORT.TT_CR7_IMPORT UNION 
SELECT 'MATCH_EVENT_ID' AS COLUMN_NAME, SUM(CASE WHEN MATCH_EVENT_ID IS NULL THEN 1 ELSE 0 END) AS NUM_NULLS, SUM(CASE WHEN MATCH_EVENT_ID IS NOT NULL THEN 1 ELSE 0 END) AS NUM_NOT_NULLS, ROUND(NUM_NULLS / COUNT(*) * 100, 2) AS PERC_MISSING FROM A_IMPORT.TT_CR7_IMPORT UNION 
SELECT 'MATCH_ID' AS COLUMN_NAME, SUM(CASE WHEN MATCH_ID IS NULL THEN 1 ELSE 0 END) AS NUM_NULLS, SUM(CASE WHEN MATCH_ID IS NOT NULL THEN 1 ELSE 0 END) AS NUM_NOT_NULLS, ROUND(NUM_NULLS / COUNT(*) * 100, 2) AS PERC_MISSING FROM A_IMPORT.TT_CR7_IMPORT UNION 
SELECT 'REMAINING_MIN' AS COLUMN_NAME, SUM(CASE WHEN REMAINING_MIN IS NULL THEN 1 ELSE 0 END) AS NUM_NULLS, SUM(CASE WHEN REMAINING_MIN IS NOT NULL THEN 1 ELSE 0 END) AS NUM_NOT_NULLS, ROUND(NUM_NULLS / COUNT(*) * 100, 2) AS PERC_MISSING FROM A_IMPORT.TT_CR7_IMPORT UNION 
SELECT 'REMAINING_MIN_1' AS COLUMN_NAME, SUM(CASE WHEN REMAINING_MIN_1 IS NULL THEN 1 ELSE 0 END) AS NUM_NULLS, SUM(CASE WHEN REMAINING_MIN_1 IS NOT NULL THEN 1 ELSE 0 END) AS NUM_NOT_NULLS, ROUND(NUM_NULLS / COUNT(*) * 100, 2) AS PERC_MISSING FROM A_IMPORT.TT_CR7_IMPORT UNION 
SELECT 'REMAINING_SEC' AS COLUMN_NAME, SUM(CASE WHEN REMAINING_SEC IS NULL THEN 1 ELSE 0 END) AS NUM_NULLS, SUM(CASE WHEN REMAINING_SEC IS NOT NULL THEN 1 ELSE 0 END) AS NUM_NOT_NULLS, ROUND(NUM_NULLS / COUNT(*) * 100, 2) AS PERC_MISSING FROM A_IMPORT.TT_CR7_IMPORT UNION 
SELECT 'SHOT_ID_NUMBER' AS COLUMN_NAME, SUM(CASE WHEN SHOT_ID_NUMBER IS NULL THEN 1 ELSE 0 END) AS NUM_NULLS, SUM(CASE WHEN SHOT_ID_NUMBER IS NOT NULL THEN 1 ELSE 0 END) AS NUM_NOT_NULLS, ROUND(NUM_NULLS / COUNT(*) * 100, 2) AS PERC_MISSING FROM A_IMPORT.TT_CR7_IMPORT UNION 
SELECT 'TEAM_ID' AS COLUMN_NAME, SUM(CASE WHEN TEAM_ID IS NULL THEN 1 ELSE 0 END) AS NUM_NULLS, SUM(CASE WHEN TEAM_ID IS NOT NULL THEN 1 ELSE 0 END) AS NUM_NOT_NULLS, ROUND(NUM_NULLS / COUNT(*) * 100, 2) AS PERC_MISSING FROM A_IMPORT.TT_CR7_IMPORT UNION 
SELECT 'TEAM_NAME' AS COLUMN_NAME, SUM(CASE WHEN TEAM_NAME IS NULL THEN 1 ELSE 0 END) AS NUM_NULLS, SUM(CASE WHEN TEAM_NAME IS NOT NULL THEN 1 ELSE 0 END) AS NUM_NOT_NULLS, ROUND(NUM_NULLS / COUNT(*) * 100, 2) AS PERC_MISSING FROM A_IMPORT.TT_CR7_IMPORT UNION 
SELECT 'LAT_LNG' AS COLUMN_NAME, SUM(CASE WHEN LAT_LNG IS NULL THEN 1 ELSE 0 END) AS NUM_NULLS, SUM(CASE WHEN LAT_LNG IS NOT NULL THEN 1 ELSE 0 END) AS NUM_NOT_NULLS, ROUND(NUM_NULLS / COUNT(*) * 100, 2) AS PERC_MISSING FROM A_IMPORT.TT_CR7_IMPORT UNION 
SELECT 'RANGE_OF_SHOT' AS COLUMN_NAME, SUM(CASE WHEN RANGE_OF_SHOT IS NULL THEN 1 ELSE 0 END) AS NUM_NULLS, SUM(CASE WHEN RANGE_OF_SHOT IS NOT NULL THEN 1 ELSE 0 END) AS NUM_NOT_NULLS, ROUND(NUM_NULLS / COUNT(*) * 100, 2) AS PERC_MISSING FROM A_IMPORT.TT_CR7_IMPORT UNION 
SELECT 'POWER_OF_SHOT_1' AS COLUMN_NAME, SUM(CASE WHEN POWER_OF_SHOT_1 IS NULL THEN 1 ELSE 0 END) AS NUM_NULLS, SUM(CASE WHEN POWER_OF_SHOT_1 IS NOT NULL THEN 1 ELSE 0 END) AS NUM_NOT_NULLS, ROUND(NUM_NULLS / COUNT(*) * 100, 2) AS PERC_MISSING FROM A_IMPORT.TT_CR7_IMPORT UNION 
SELECT 'REMAINING_SEC_1' AS COLUMN_NAME, SUM(CASE WHEN REMAINING_SEC_1 IS NULL THEN 1 ELSE 0 END) AS NUM_NULLS, SUM(CASE WHEN REMAINING_SEC_1 IS NOT NULL THEN 1 ELSE 0 END) AS NUM_NOT_NULLS, ROUND(NUM_NULLS / COUNT(*) * 100, 2) AS PERC_MISSING FROM A_IMPORT.TT_CR7_IMPORT UNION 
SELECT 'POWER_OF_SHOT' AS COLUMN_NAME, SUM(CASE WHEN POWER_OF_SHOT IS NULL THEN 1 ELSE 0 END) AS NUM_NULLS, SUM(CASE WHEN POWER_OF_SHOT IS NOT NULL THEN 1 ELSE 0 END) AS NUM_NOT_NULLS, ROUND(NUM_NULLS / COUNT(*) * 100, 2) AS PERC_MISSING FROM A_IMPORT.TT_CR7_IMPORT UNION 
SELECT 'SHOT_BASICS' AS COLUMN_NAME, SUM(CASE WHEN SHOT_BASICS IS NULL THEN 1 ELSE 0 END) AS NUM_NULLS, SUM(CASE WHEN SHOT_BASICS IS NOT NULL THEN 1 ELSE 0 END) AS NUM_NOT_NULLS, ROUND(NUM_NULLS / COUNT(*) * 100, 2) AS PERC_MISSING FROM A_IMPORT.TT_CR7_IMPORT UNION 
SELECT 'TYPE_OF_SHOT' AS COLUMN_NAME, SUM(CASE WHEN TYPE_OF_SHOT IS NULL THEN 1 ELSE 0 END) AS NUM_NULLS, SUM(CASE WHEN TYPE_OF_SHOT IS NOT NULL THEN 1 ELSE 0 END) AS NUM_NOT_NULLS, ROUND(NUM_NULLS / COUNT(*) * 100, 2) AS PERC_MISSING FROM A_IMPORT.TT_CR7_IMPORT UNION 
SELECT 'LOCATION_Y' AS COLUMN_NAME, SUM(CASE WHEN LOCATION_Y IS NULL THEN 1 ELSE 0 END) AS NUM_NULLS, SUM(CASE WHEN LOCATION_Y IS NOT NULL THEN 1 ELSE 0 END) AS NUM_NOT_NULLS, ROUND(NUM_NULLS / COUNT(*) * 100, 2) AS PERC_MISSING FROM A_IMPORT.TT_CR7_IMPORT UNION 
SELECT 'TYPE_OF_COMBINED_SHOT' AS COLUMN_NAME, SUM(CASE WHEN TYPE_OF_COMBINED_SHOT IS NULL THEN 1 ELSE 0 END) AS NUM_NULLS, SUM(CASE WHEN TYPE_OF_COMBINED_SHOT IS NOT NULL THEN 1 ELSE 0 END) AS NUM_NOT_NULLS, ROUND(NUM_NULLS / COUNT(*) * 100, 2) AS PERC_MISSING FROM A_IMPORT.TT_CR7_IMPORT;



SELECT 'AREA_OF_SHOT' AS COLUMN_NAME, SUM(CASE WHEN AREA_OF_SHOT IS NULL THEN 1 ELSE 0 END) AS NUM_NULLS, SUM(CASE WHEN AREA_OF_SHOT IS NOT NULL THEN 1 ELSE 0 END) AS NUM_NOT_NULLS, ROUND(NUM_NULLS / COUNT(*) * 100, 2) AS PERC_MISSING FROM B_CLEANING.T_CR7_CLEANING UNION 
SELECT 'DISTANCE_OF_SHOT' AS COLUMN_NAME, SUM(CASE WHEN DISTANCE_OF_SHOT IS NULL THEN 1 ELSE 0 END) AS NUM_NULLS, SUM(CASE WHEN DISTANCE_OF_SHOT IS NOT NULL THEN 1 ELSE 0 END) AS NUM_NOT_NULLS, ROUND(NUM_NULLS / COUNT(*) * 100, 2) AS PERC_MISSING FROM B_CLEANING.T_CR7_CLEANING UNION 
SELECT 'GAME_SEASON' AS COLUMN_NAME, SUM(CASE WHEN GAME_SEASON IS NULL THEN 1 ELSE 0 END) AS NUM_NULLS, SUM(CASE WHEN GAME_SEASON IS NOT NULL THEN 1 ELSE 0 END) AS NUM_NOT_NULLS, ROUND(NUM_NULLS / COUNT(*) * 100, 2) AS PERC_MISSING FROM B_CLEANING.T_CR7_CLEANING UNION 
SELECT 'ID' AS COLUMN_NAME, SUM(CASE WHEN ID IS NULL THEN 1 ELSE 0 END) AS NUM_NULLS, SUM(CASE WHEN ID IS NOT NULL THEN 1 ELSE 0 END) AS NUM_NOT_NULLS, ROUND(NUM_NULLS / COUNT(*) * 100, 2) AS PERC_MISSING FROM B_CLEANING.T_CR7_CLEANING UNION 
SELECT 'IS_COMBINED' AS COLUMN_NAME, SUM(CASE WHEN IS_COMBINED IS NULL THEN 1 ELSE 0 END) AS NUM_NULLS, SUM(CASE WHEN IS_COMBINED IS NOT NULL THEN 1 ELSE 0 END) AS NUM_NOT_NULLS, ROUND(NUM_NULLS / COUNT(*) * 100, 2) AS PERC_MISSING FROM B_CLEANING.T_CR7_CLEANING UNION 
SELECT 'KNOCKOUT_MATCH' AS COLUMN_NAME, SUM(CASE WHEN KNOCKOUT_MATCH IS NULL THEN 1 ELSE 0 END) AS NUM_NULLS, SUM(CASE WHEN KNOCKOUT_MATCH IS NOT NULL THEN 1 ELSE 0 END) AS NUM_NOT_NULLS, ROUND(NUM_NULLS / COUNT(*) * 100, 2) AS PERC_MISSING FROM B_CLEANING.T_CR7_CLEANING UNION 
SELECT 'LOCATION_X' AS COLUMN_NAME, SUM(CASE WHEN LOCATION_X IS NULL THEN 1 ELSE 0 END) AS NUM_NULLS, SUM(CASE WHEN LOCATION_X IS NOT NULL THEN 1 ELSE 0 END) AS NUM_NOT_NULLS, ROUND(NUM_NULLS / COUNT(*) * 100, 2) AS PERC_MISSING FROM B_CLEANING.T_CR7_CLEANING UNION 
SELECT 'LOCATION_Y' AS COLUMN_NAME, SUM(CASE WHEN LOCATION_Y IS NULL THEN 1 ELSE 0 END) AS NUM_NULLS, SUM(CASE WHEN LOCATION_Y IS NOT NULL THEN 1 ELSE 0 END) AS NUM_NOT_NULLS, ROUND(NUM_NULLS / COUNT(*) * 100, 2) AS PERC_MISSING FROM B_CLEANING.T_CR7_CLEANING UNION 
SELECT 'LONGITUDE' AS COLUMN_NAME, SUM(CASE WHEN LONGITUDE IS NULL THEN 1 ELSE 0 END) AS NUM_NULLS, SUM(CASE WHEN LONGITUDE IS NOT NULL THEN 1 ELSE 0 END) AS NUM_NOT_NULLS, ROUND(NUM_NULLS / COUNT(*) * 100, 2) AS PERC_MISSING FROM B_CLEANING.T_CR7_CLEANING UNION 
SELECT 'MATCH_EVENT_ID' AS COLUMN_NAME, SUM(CASE WHEN MATCH_EVENT_ID IS NULL THEN 1 ELSE 0 END) AS NUM_NULLS, SUM(CASE WHEN MATCH_EVENT_ID IS NOT NULL THEN 1 ELSE 0 END) AS NUM_NOT_NULLS, ROUND(NUM_NULLS / COUNT(*) * 100, 2) AS PERC_MISSING FROM B_CLEANING.T_CR7_CLEANING UNION 
SELECT 'MATCH_ID' AS COLUMN_NAME, SUM(CASE WHEN MATCH_ID IS NULL THEN 1 ELSE 0 END) AS NUM_NULLS, SUM(CASE WHEN MATCH_ID IS NOT NULL THEN 1 ELSE 0 END) AS NUM_NOT_NULLS, ROUND(NUM_NULLS / COUNT(*) * 100, 2) AS PERC_MISSING FROM B_CLEANING.T_CR7_CLEANING UNION 
SELECT 'POWER_OF_SHOT' AS COLUMN_NAME, SUM(CASE WHEN POWER_OF_SHOT IS NULL THEN 1 ELSE 0 END) AS NUM_NULLS, SUM(CASE WHEN POWER_OF_SHOT IS NOT NULL THEN 1 ELSE 0 END) AS NUM_NOT_NULLS, ROUND(NUM_NULLS / COUNT(*) * 100, 2) AS PERC_MISSING FROM B_CLEANING.T_CR7_CLEANING UNION 
SELECT 'RANGE_OF_SHOT_IN_FEETS' AS COLUMN_NAME, SUM(CASE WHEN RANGE_OF_SHOT_IN_FEETS IS NULL THEN 1 ELSE 0 END) AS NUM_NULLS, SUM(CASE WHEN RANGE_OF_SHOT_IN_FEETS IS NOT NULL THEN 1 ELSE 0 END) AS NUM_NOT_NULLS, ROUND(NUM_NULLS / COUNT(*) * 100, 2) AS PERC_MISSING FROM B_CLEANING.T_CR7_CLEANING UNION 
SELECT 'REMAINING_MIN' AS COLUMN_NAME, SUM(CASE WHEN REMAINING_MIN IS NULL THEN 1 ELSE 0 END) AS NUM_NULLS, SUM(CASE WHEN REMAINING_MIN IS NOT NULL THEN 1 ELSE 0 END) AS NUM_NOT_NULLS, ROUND(NUM_NULLS / COUNT(*) * 100, 2) AS PERC_MISSING FROM B_CLEANING.T_CR7_CLEANING UNION 
SELECT 'TEAM_AWAY' AS COLUMN_NAME, SUM(CASE WHEN TEAM_AWAY IS NULL THEN 1 ELSE 0 END) AS NUM_NULLS, SUM(CASE WHEN TEAM_AWAY IS NOT NULL THEN 1 ELSE 0 END) AS NUM_NOT_NULLS, ROUND(NUM_NULLS / COUNT(*) * 100, 2) AS PERC_MISSING FROM B_CLEANING.T_CR7_CLEANING UNION 
SELECT 'TEAM_ID' AS COLUMN_NAME, SUM(CASE WHEN TEAM_ID IS NULL THEN 1 ELSE 0 END) AS NUM_NULLS, SUM(CASE WHEN TEAM_ID IS NOT NULL THEN 1 ELSE 0 END) AS NUM_NOT_NULLS, ROUND(NUM_NULLS / COUNT(*) * 100, 2) AS PERC_MISSING FROM B_CLEANING.T_CR7_CLEANING UNION 
SELECT 'TYPE_OF_SHOT' AS COLUMN_NAME, SUM(CASE WHEN TYPE_OF_SHOT IS NULL THEN 1 ELSE 0 END) AS NUM_NULLS, SUM(CASE WHEN TYPE_OF_SHOT IS NOT NULL THEN 1 ELSE 0 END) AS NUM_NOT_NULLS, ROUND(NUM_NULLS / COUNT(*) * 100, 2) AS PERC_MISSING FROM B_CLEANING.T_CR7_CLEANING UNION 
SELECT 'LATITUDE' AS COLUMN_NAME, SUM(CASE WHEN LATITUDE IS NULL THEN 1 ELSE 0 END) AS NUM_NULLS, SUM(CASE WHEN LATITUDE IS NOT NULL THEN 1 ELSE 0 END) AS NUM_NOT_NULLS, ROUND(NUM_NULLS / COUNT(*) * 100, 2) AS PERC_MISSING FROM B_CLEANING.T_CR7_CLEANING UNION 
SELECT 'SHOT_ID_NUMBER' AS COLUMN_NAME, SUM(CASE WHEN SHOT_ID_NUMBER IS NULL THEN 1 ELSE 0 END) AS NUM_NULLS, SUM(CASE WHEN SHOT_ID_NUMBER IS NOT NULL THEN 1 ELSE 0 END) AS NUM_NOT_NULLS, ROUND(NUM_NULLS / COUNT(*) * 100, 2) AS PERC_MISSING FROM B_CLEANING.T_CR7_CLEANING UNION 
SELECT 'TEAM_HOME' AS COLUMN_NAME, SUM(CASE WHEN TEAM_HOME IS NULL THEN 1 ELSE 0 END) AS NUM_NULLS, SUM(CASE WHEN TEAM_HOME IS NOT NULL THEN 1 ELSE 0 END) AS NUM_NOT_NULLS, ROUND(NUM_NULLS / COUNT(*) * 100, 2) AS PERC_MISSING FROM B_CLEANING.T_CR7_CLEANING UNION 
SELECT 'TYPE_OF_SHOT_NUM' AS COLUMN_NAME, SUM(CASE WHEN TYPE_OF_SHOT_NUM IS NULL THEN 1 ELSE 0 END) AS NUM_NULLS, SUM(CASE WHEN TYPE_OF_SHOT_NUM IS NOT NULL THEN 1 ELSE 0 END) AS NUM_NOT_NULLS, ROUND(NUM_NULLS / COUNT(*) * 100, 2) AS PERC_MISSING FROM B_CLEANING.T_CR7_CLEANING UNION 
SELECT 'IS_GOAL' AS COLUMN_NAME, SUM(CASE WHEN IS_GOAL IS NULL THEN 1 ELSE 0 END) AS NUM_NULLS, SUM(CASE WHEN IS_GOAL IS NOT NULL THEN 1 ELSE 0 END) AS NUM_NOT_NULLS, ROUND(NUM_NULLS / COUNT(*) * 100, 2) AS PERC_MISSING FROM B_CLEANING.T_CR7_CLEANING UNION 
SELECT 'RANGE_OF_SHOT' AS COLUMN_NAME, SUM(CASE WHEN RANGE_OF_SHOT IS NULL THEN 1 ELSE 0 END) AS NUM_NULLS, SUM(CASE WHEN RANGE_OF_SHOT IS NOT NULL THEN 1 ELSE 0 END) AS NUM_NOT_NULLS, ROUND(NUM_NULLS / COUNT(*) * 100, 2) AS PERC_MISSING FROM B_CLEANING.T_CR7_CLEANING UNION 
SELECT 'REMAINING_SEC' AS COLUMN_NAME, SUM(CASE WHEN REMAINING_SEC IS NULL THEN 1 ELSE 0 END) AS NUM_NULLS, SUM(CASE WHEN REMAINING_SEC IS NOT NULL THEN 1 ELSE 0 END) AS NUM_NOT_NULLS, ROUND(NUM_NULLS / COUNT(*) * 100, 2) AS PERC_MISSING FROM B_CLEANING.T_CR7_CLEANING UNION 
SELECT 'SHOT_BASICS' AS COLUMN_NAME, SUM(CASE WHEN SHOT_BASICS IS NULL THEN 1 ELSE 0 END) AS NUM_NULLS, SUM(CASE WHEN SHOT_BASICS IS NOT NULL THEN 1 ELSE 0 END) AS NUM_NOT_NULLS, ROUND(NUM_NULLS / COUNT(*) * 100, 2) AS PERC_MISSING FROM B_CLEANING.T_CR7_CLEANING UNION 
SELECT 'TEAM_NAME' AS COLUMN_NAME, SUM(CASE WHEN TEAM_NAME IS NULL THEN 1 ELSE 0 END) AS NUM_NULLS, SUM(CASE WHEN TEAM_NAME IS NOT NULL THEN 1 ELSE 0 END) AS NUM_NOT_NULLS, ROUND(NUM_NULLS / COUNT(*) * 100, 2) AS PERC_MISSING FROM B_CLEANING.T_CR7_CLEANING UNION 
SELECT 'DATE_OF_GAME' AS COLUMN_NAME, SUM(CASE WHEN DATE_OF_GAME IS NULL THEN 1 ELSE 0 END) AS NUM_NULLS, SUM(CASE WHEN DATE_OF_GAME IS NOT NULL THEN 1 ELSE 0 END) AS NUM_NOT_NULLS, ROUND(NUM_NULLS / COUNT(*) * 100, 2) AS PERC_MISSING FROM B_CLEANING.T_CR7_CLEANING;





select *
from ronaldo.c_dm.l_team;










SELECT count(distinct shot_id_number) as shots
FROM RONALDO.A_IMPORT.TT_CR7_IMPORT;


select match_ids, game_season_ids, shot_basics_ids, distance_of_shot, is_goal
from ronaldo.c_dm.f_ronaldo_shots
where shot_basics_ids=-1 and date_of_game='2008-02-26' and type_of_shot_ids=3;

select *
from ronaldo.c_dm.l_shot_basics
order by shot_basics_ids