USE DATABASE RONALDO;

CREATE OR REPLACE SCHEMA RONALDO.C_DM;

USE SCHEMA RONALDO.C_DM;

CREATE TABLE L_AREA_OF_SHOT AS 
SELECT *
FROM RONALDO.C_SA.S_AREA_OF_SHOT;



CREATE TABLE L_SHOT_BASICS AS 
SELECT *
FROM RONALDO.C_SA.S_SHOT_BASICS;


CREATE TABLE L_TEAM AS 
SELECT *
FROM RONALDO.C_SA.S_TEAM;

CREATE TABLE L_TYPE_OF_SHOT AS 
SELECT *
FROM RONALDO.C_SA.S_TYPE_OF_SHOT;


CREATE TABLE L_GAME_SEASON AS 
SELECT *
FROM RONALDO.C_SA.S_GAME_SEASON;

CREATE TABLE L_MATCH AS 
SELECT *
FROM RONALDO.C_SA.S_MATCH;


CREATE TABLE F_RONALDO_SHOTS AS 
SELECT *
FROM RONALDO.C_SA.SF_RONALDO_SHOTS;



